blank_issues_enabled: false
contact_links:
  - name: Changes to Website Functionality
    url: https://github.com/TheOdinProject/theodinproject
    about: "For changes to website functionality, check out Odin's web app repository"

